# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9756cf55eeb785450755404e7bb97e49e5241f1e73ddc726782612a3eae803b813c60c97f493758f91ad9473a06ee5fe202ed7776819d4c72ca18493c5209d74

test:
  secret_key_base: 6bf9461b115fbe3c7f1fd90d9c9b4564b56d2c82a4a90ba64092deaba136bfa1d2eb4d3914fe988524b21108488cc344242bed7602794a4f0cad0c1ca53922a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
